import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

const States = [
  "text",
  "Text",
  "eTxt",
  "exTt",
  "extT",
  "extt",
  "extt",
  "extt",
  "extT",
  "exTt",
  "eTxt",
  "Text",
  "text",
  "text",
];

const Logo = () => {
  const [frame, setFrame] = useState(0);
  useEffect(() => {
    const i = setTimeout(() => setFrame((frame + 1) % States.length), 300);
    return () => clearTimeout(i);
  }, [frame]);

  return <span className="mt-8 text-4xl">{States[frame]}</span>;
};

const Home: NextPage = () => {
  return (
    <div className="flex min-h-screen flex-col">
      <Head>
        <title>Extt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container prose prose-stone mx-auto flex max-w-2xl flex-grow flex-col items-center justify-center px-4 py-16 dark:prose-invert">
        <Image alt="logo" width={128} height={128} src="/icon.png" />
        <Logo />
        <p className="text-xs opacity-50">coming soon...</p>
      </main>
      <footer className="container mx-auto max-w-2xl p-4 text-xs opacity-50">
        Copyright © 2022 extt.app
      </footer>
    </div>
  );
};

export default Home;
