import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

const States = [
  "text",
  "Text",
  "eTxt",
  "exTt",
  "extT",
  "extt",
  "extt",
  "extt",
  "extT",
  "exTt",
  "eTxt",
  "Text",
  "text",
  "text",
];

const Logo = () => {
  const [frame, setFrame] = useState(0);
  useEffect(() => {
    const i = setTimeout(() => setFrame((frame + 1) % States.length), 300);
    return () => clearTimeout(i);
  }, [frame]);

  return <span className="text-4xl mt-8">{States[frame]}</span>;
};

const Home: NextPage = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Head>
        <title>Extt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-grow container mx-auto max-w-2xl prose prose-stone dark:prose-invert px-4 py-16 flex flex-col justify-center items-center">
        <Image alt="logo" width={128} height={128} src="/icon.png" />
        <Logo />
        <p className="text-xs opacity-50">coming soon...</p>
      </main>
      <footer className="text-xs container mx-auto max-w-2xl p-4 opacity-50">
        Copyright © 2022 extt.app
      </footer>
    </div>
  );
};

export default Home;
